// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartManagement.Data;

#nullable disable

namespace SmartManagement.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250327012946_remove S3KEY from TransactionDocument")]
    partial class removeS3KEYfromTransactionDocument
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.Property<int>("RolesRoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionsId", "RolesRoleId");

                    b.HasIndex("RolesRoleId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("RolesRoleId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("SmartManagement.Core.Models.CategoryExpenseAndIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ISExpense")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CategoriesExpenseAndIncome");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "קניות בסופר, מסעדות ובתי קפה",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "אוכל"
                        },
                        new
                        {
                            Id = 2,
                            Description = "דלק, תחבורה ציבורית, רכב",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "תחבורה"
                        },
                        new
                        {
                            Id = 3,
                            Description = "שכר דירה, משכנתא, חשבונות בית",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "דיור"
                        },
                        new
                        {
                            Id = 4,
                            Description = "קניית בגדים, נעליים ואביזרים",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "ביגוד והנעלה"
                        },
                        new
                        {
                            Id = 5,
                            Description = "ביטוח רפואי, תרופות, טיפולי שיניים",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "בריאות"
                        },
                        new
                        {
                            Id = 6,
                            Description = "קולנוע, תיאטרון, טיולים",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "בילויים ופנאי"
                        },
                        new
                        {
                            Id = 7,
                            Description = "שכר לימוד, ספרים, קורסים",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "חינוך"
                        },
                        new
                        {
                            Id = 8,
                            Description = "ריהוט, כלי בית, תחזוקה",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "מוצרים לבית"
                        },
                        new
                        {
                            Id = 9,
                            Description = "ארנונה, חשמל, מים, גז, אינטרנט",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "תשלומים חודשיים"
                        },
                        new
                        {
                            Id = 10,
                            Description = "הוצאות בלתי צפויות",
                            ISExpense = true,
                            IsIncome = false,
                            Name = "שונות"
                        },
                        new
                        {
                            Id = 11,
                            Description = "הכנסה מעבודה חודשית",
                            ISExpense = false,
                            IsIncome = true,
                            Name = "משכורת"
                        },
                        new
                        {
                            Id = 12,
                            Description = "רווחים מעסק עצמאי",
                            ISExpense = false,
                            IsIncome = true,
                            Name = "הכנסה מעסק"
                        },
                        new
                        {
                            Id = 13,
                            Description = "רווחים מהשקעות במניות, קרנות",
                            ISExpense = false,
                            IsIncome = true,
                            Name = "השקעות"
                        },
                        new
                        {
                            Id = 14,
                            Description = "הכנסות מביטוח לאומי, פנסיה",
                            ISExpense = false,
                            IsIncome = true,
                            Name = "קצבאות"
                        },
                        new
                        {
                            Id = 15,
                            Description = "הכנסות צדדיות, עבודות זמניות",
                            ISExpense = false,
                            IsIncome = true,
                            Name = "הכנסות נוספות"
                        });
                });

            modelBuilder.Entity("SmartManagement.Core.Models.ExpenseAndIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FixedExpenseAndIncomeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("TransactionDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeTransaction")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FixedExpenseAndIncomeId");

                    b.HasIndex("TransactionDocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("ExpensesAndIncomes");
                });

            modelBuilder.Entity("SmartManagement.Core.Models.FixedExpenseAndIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TypeTransaction")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FixedExpensesAndIncomes");
                });

            modelBuilder.Entity("SmartManagement.Core.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create new users",
                            Name = "Users.Create"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Delete users",
                            Name = "Users.Delete"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Edit users",
                            Name = "Users.Update"
                        },
                        new
                        {
                            Id = 4,
                            Description = "View user details",
                            Name = "Users.View"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Create files",
                            Name = "Files.Create"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Delete files",
                            Name = "Files.Delete"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Edit files",
                            Name = "Files.Update"
                        },
                        new
                        {
                            Id = 8,
                            Description = "View files",
                            Name = "Files.View"
                        });
                });

            modelBuilder.Entity("SmartManagement.Core.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("SmartManagement.Core.Models.TransactionDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TransactionDocuments");
                });

            modelBuilder.Entity("SmartManagement.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("SmartManagement.Core.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartManagement.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("SmartManagement.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartManagement.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartManagement.Core.Models.ExpenseAndIncome", b =>
                {
                    b.HasOne("SmartManagement.Core.Models.CategoryExpenseAndIncome", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartManagement.Core.Models.FixedExpenseAndIncome", "FixedExpenseAndIncome")
                        .WithMany()
                        .HasForeignKey("FixedExpenseAndIncomeId");

                    b.HasOne("SmartManagement.Core.Models.TransactionDocument", "TransactionDocument")
                        .WithMany()
                        .HasForeignKey("TransactionDocumentId");

                    b.HasOne("SmartManagement.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FixedExpenseAndIncome");

                    b.Navigation("TransactionDocument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartManagement.Core.Models.FixedExpenseAndIncome", b =>
                {
                    b.HasOne("SmartManagement.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
